version: "3.9"

services:
  pod-cart-sim:
    image: pod-cart-sim:local
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    env_file:
      - ./.env
    environment:
      PORT: "5002"
      PRODUCT_FILE: /data/products.json
    volumes:
      - ${APP_DATA_DIR}:/data
