services:
  pod-cart-sim:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    env_file:
      - ./.env
    environment:
      FLASK_APP: "app:app"
      FLASK_DEBUG: "1"
      PORT: "5002"
      PRODUCT_FILE: /data/products.json
    command: ["flask", "--app", "app:app", "run", "--host=0.0.0.0", "--port=5002", "--debug"]
    volumes:
      - ./:/app
      - ${HOME}/Documents/kozakura/apps_data/pod_cart_sim:/data
